// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Repositories;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20261008151347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("IsDone");

                    b.HasIndex("Priority");

                    b.ToTable("Todos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3b5a1d2-1c9b-4f2e-9e2a-8a1b2c3d4e5f"),
                            Description = "Milk, eggs, bread",
                            DueDate = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 1,
                            Title = "Buy groceries"
                        },
                        new
                        {
                            Id = new Guid("a2c4e6f8-9b7d-4a3c-8f1e-0d9c8b7a6e5d"),
                            Description = "Complete the summary and send to manager",
                            DueDate = new DateTime(2026, 10, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 2,
                            Title = "Finish project report"
                        },
                        new
                        {
                            Id = new Guid("c0b1a2d3-e4f5-6789-abcd-0123456789ab"),
                            Description = "Fix kitchen sink leak",
                            DueDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 0,
                            Title = "Call plumber"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d3e-9f0a-1234abcd5678"),
                            Description = "Read 50 pages of the new novel",
                            DueDate = new DateTime(2026, 10, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = true,
                            Priority = 0,
                            Title = "Read book"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
